### ISSUE TITLE
The documentation uses "Jenkins CI" instead of "Jenkins"

### ISSUE THREAD

**Issue by oleg-nenashev** [Novartis/Jenkins-LSCI#1]
Hi, Just a minor glitch. Starting from Jenkins 2 we do not use the "Jenkins CI" term anymore since the application area of Jenkins is much wider. Please use "Jenkins" in docs. FTR "Branding" section in https://jenkins.io/press/

**Comment by imoutsatsos** [comment]
References to Jenkins in documentation are now updated to reflect the preferred name. In addition, an attribution paragraph was added to the 'readme' file to clarify Jenkins-Jenkins-LSCI relationship and use of name and logo.
